<?xml version='1.0' encoding='UTF-8'?><!-- Published by XML-WS Runtime (https://github.com/eclipse-ee4j/metro-jax-ws). Runtime's version is Eclipse Metro/4.0.4.payara-p1 (FISH-10142-Metro-4.0.4-fa01c0b; 2025-07-11T17:44:37+0100) XMLWS-Impl/4.0.3 XMLWS-API/4.0.2 XMLB-Impl/4.0.5 XMLB-API/4.0.2 git-revision#fa01c0b. --><xs:schema xmlns:tns="http://ws.relojservidor.una.ac.cr/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://ws.relojservidor.una.ac.cr/">

<xs:element name="eliminarEmpleado" type="tns:eliminarEmpleado"/>

<xs:element name="eliminarEmpleadoResponse" type="tns:eliminarEmpleadoResponse"/>

<xs:element name="empleadoDto" type="tns:empleadoDto"/>

<xs:element name="guardarEmpleado" type="tns:guardarEmpleado"/>

<xs:element name="guardarEmpleadoResponse" type="tns:guardarEmpleadoResponse"/>

<xs:element name="obtenerEmpleadoPorId" type="tns:obtenerEmpleadoPorId"/>

<xs:element name="obtenerEmpleadoPorIdResponse" type="tns:obtenerEmpleadoPorIdResponse"/>

<xs:element name="obtenerEmpleados" type="tns:obtenerEmpleados"/>

<xs:element name="obtenerEmpleadosResponse" type="tns:obtenerEmpleadosResponse"/>

<xs:complexType name="empleadoDto">
<xs:sequence>
<xs:element name="apellidos" type="xs:string" minOccurs="0"/>
<xs:element name="cedula" type="xs:string" minOccurs="0"/>
<xs:element name="clave" type="xs:string" minOccurs="0"/>
<xs:element name="esAdmin" type="xs:int" minOccurs="0"/>
<xs:element name="fechaNacimiento" type="xs:string" minOccurs="0"/>
<xs:element name="folio" type="xs:string" minOccurs="0"/>
<xs:element name="foto" type="xs:base64Binary" minOccurs="0"/>
<xs:element name="id" type="xs:long" minOccurs="0"/>
<xs:element name="nombre" type="xs:string" minOccurs="0"/>
<xs:element name="salarioHora" type="xs:double" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="listaEmpleadoDto">
<xs:sequence>
<xs:element name="empleados" type="tns:empleadoDto" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="guardarEmpleado">
<xs:sequence>
<xs:element name="empleado" type="tns:empleadoDto" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="guardarEmpleadoResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="respuesta">
<xs:sequence>
<xs:element name="exito" type="xs:boolean"/>
<xs:element name="mensaje" type="xs:string" minOccurs="0"/>
<xs:any processContents="lax" namespace="##other"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerEmpleadoPorId">
<xs:sequence>
<xs:element name="id" type="xs:long" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerEmpleadoPorIdResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerEmpleados">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="obtenerEmpleadosResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="eliminarEmpleado">
<xs:sequence>
<xs:element name="id" type="xs:long" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="eliminarEmpleadoResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:schema>