<?xml version='1.0' encoding='UTF-8'?><!-- Published by XML-WS Runtime (https://github.com/eclipse-ee4j/metro-jax-ws). Runtime's version is Eclipse Metro/4.0.4.payara-p1 (FISH-10142-Metro-4.0.4-fa01c0b; 2025-07-11T17:44:37+0100) XMLWS-Impl/4.0.3 XMLWS-API/4.0.2 XMLB-Impl/4.0.5 XMLB-API/4.0.2 git-revision#fa01c0b. --><xs:schema xmlns:tns="http://ws.relojservidor.una.ac.cr/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://ws.relojservidor.una.ac.cr/">

<xs:element name="generarPlanilla" type="tns:generarPlanilla"/>

<xs:element name="generarPlanillaResponse" type="tns:generarPlanillaResponse"/>

<xs:element name="guardarPlanilla" type="tns:guardarPlanilla"/>

<xs:element name="guardarPlanillaResponse" type="tns:guardarPlanillaResponse"/>

<xs:element name="listaPlanillaFilaDto" type="tns:listaPlanillaFilaDto"/>

<xs:element name="obtenerPlanillaPorId" type="tns:obtenerPlanillaPorId"/>

<xs:element name="obtenerPlanillaPorIdResponse" type="tns:obtenerPlanillaPorIdResponse"/>

<xs:element name="obtenerPlanillas" type="tns:obtenerPlanillas"/>

<xs:element name="obtenerPlanillasResponse" type="tns:obtenerPlanillasResponse"/>

<xs:element name="planillaFilaDto" type="tns:planillaFilaDto"/>

<xs:complexType name="listaPlanillaFilaDto">
<xs:sequence>
<xs:element name="filas" type="tns:planillaFilaDto" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="planillaFilaDto">
<xs:sequence>
<xs:element name="folioEmpleado" type="xs:string" minOccurs="0"/>
<xs:element name="nombreEmpleado" type="xs:string" minOccurs="0"/>
<xs:element name="horasOrdinarias" type="xs:double" minOccurs="0"/>
<xs:element name="horasExtras" type="xs:double" minOccurs="0"/>
<xs:element name="horasDobles" type="xs:double" minOccurs="0"/>
<xs:element name="salarioMensual" type="xs:double" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPlanillaPorId">
<xs:sequence>
<xs:element name="id" type="xs:long" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPlanillaPorIdResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="respuesta">
<xs:sequence>
<xs:element name="exito" type="xs:boolean"/>
<xs:element name="mensaje" type="xs:string" minOccurs="0"/>
<xs:any processContents="lax" namespace="##other"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="guardarPlanilla">
<xs:sequence>
<xs:element name="planilla" type="tns:planillaDto" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="planillaDto">
<xs:sequence>
<xs:element name="anio" type="xs:int" minOccurs="0"/>
<xs:element name="detalles" type="tns:detallePlanillaDto" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="fechaGeneracion" type="xs:string" minOccurs="0"/>
<xs:element name="id" type="xs:long" minOccurs="0"/>
<xs:element name="mes" type="xs:int" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="detallePlanillaDto">
<xs:sequence>
<xs:element name="empleadoId" type="xs:long" minOccurs="0"/>
<xs:element name="horasDobles" type="xs:int" minOccurs="0"/>
<xs:element name="horasExtras" type="xs:int" minOccurs="0"/>
<xs:element name="horasOrdinarias" type="xs:int" minOccurs="0"/>
<xs:element name="id" type="xs:long" minOccurs="0"/>
<xs:element name="planillaId" type="xs:long" minOccurs="0"/>
<xs:element name="salarioTotal" type="xs:double" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="guardarPlanillaResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPlanillas">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="obtenerPlanillasResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="generarPlanilla">
<xs:sequence>
<xs:element name="mes" type="xs:int"/>
<xs:element name="anio" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="generarPlanillaResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuesta" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:schema>